2022-04-23 18:10:28,730 INFO    MainThread:281 [internal.py:wandb_internal():93] W&B internal server running at pid: 281, started at: 2022-04-23 18:10:28.730362
2022-04-23 18:10:28,733 DEBUG   SenderThread:281 [sender.py:send():232] send: header
2022-04-23 18:10:28,733 INFO    WriterThread:281 [datastore.py:open_for_write():75] open: /content/elastic-infogan/wandb/run-20220423_181027-okd0kg6k/run-okd0kg6k.wandb
2022-04-23 18:10:59,095 WARNING MainThread:281 [internal.py:wandb_internal():153] Internal process interrupt: 1
2022-04-23 18:10:59,874 WARNING MainThread:281 [internal.py:wandb_internal():153] Internal process interrupt: 2
2022-04-23 18:10:59,874 ERROR   MainThread:281 [internal.py:wandb_internal():156] Internal process interrupted.
2022-04-23 18:11:00,738 INFO    WriterThread:281 [datastore.py:close():279] close: /content/elastic-infogan/wandb/run-20220423_181027-okd0kg6k/run-okd0kg6k.wandb
2022-04-23 18:11:00,738 INFO    SenderThread:281 [sender.py:finish():1106] shutting down sender
2022-04-23 18:11:00,765 INFO    HandlerThread:281 [handler.py:finish():806] shutting down handler
2022-04-23 18:11:00,765 INFO    MainThread:281 [internal.py:handle_exit():80] Internal process exited
