2022-04-23 18:10:27,900 INFO    MainThread:263 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-04-23 18:10:27,900 INFO    MainThread:263 [wandb_setup.py:_flush():75] Loading settings from /content/elastic-infogan/wandb/settings
2022-04-23 18:10:27,900 INFO    MainThread:263 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-23 18:10:27,900 INFO    MainThread:263 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': 'main.py'}
2022-04-23 18:10:27,901 INFO    MainThread:263 [wandb_setup.py:_flush():75] Applying login settings: {'api_key': '***REDACTED***'}
2022-04-23 18:10:27,901 INFO    MainThread:263 [wandb_setup.py:_flush():75] Applying login settings: {'anonymous': 'must'}
2022-04-23 18:10:27,901 INFO    MainThread:263 [wandb_init.py:_log_setup():437] Logging user logs to /content/elastic-infogan/wandb/run-20220423_181027-okd0kg6k/logs/debug.log
2022-04-23 18:10:27,901 INFO    MainThread:263 [wandb_init.py:_log_setup():438] Logging internal logs to /content/elastic-infogan/wandb/run-20220423_181027-okd0kg6k/logs/debug-internal.log
2022-04-23 18:10:27,901 INFO    MainThread:263 [wandb_init.py:init():471] calling init triggers
2022-04-23 18:10:27,901 INFO    MainThread:263 [wandb_init.py:init():475] wandb.init called with sweep_config: {}
config: {'gan_type': 'infoGAN', 'dataset': 'mnist', 'split': '', 'epoch': 3, 'batch_size': 64, 'ind': 1, 'input_size': 28, 'save_dir': 'models', 'result_dir': 'results', 'log_dir': 'logs', 'lrG': 0.0002, 'mytemp': 1.0, 'klwt': 10.0, 'lrD': 0.0002, 'beta1': 0.5, 'beta2': 0.999, 'gpu_mode': True, 'benchmark_mode': True}
2022-04-23 18:10:27,901 INFO    MainThread:263 [wandb_init.py:init():524] starting backend
2022-04-23 18:10:27,901 INFO    MainThread:263 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-23 18:10:27,908 INFO    MainThread:263 [backend.py:ensure_launched():217] starting backend process...
2022-04-23 18:10:27,913 INFO    MainThread:263 [backend.py:ensure_launched():222] started backend process with pid: 281
2022-04-23 18:10:27,925 INFO    MainThread:263 [wandb_init.py:init():533] backend started and connected
2022-04-23 18:10:27,928 INFO    MainThread:263 [wandb_init.py:init():597] updated telemetry
2022-04-23 18:10:27,965 INFO    MainThread:263 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2022-04-23 18:10:27,976 ERROR   MainThread:263 [wandb_init.py:init():1022] error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_init.py", line 995, in init
    run = wi.init()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_init.py", line 629, in init
    run_result = backend.interface.communicate_run(run, timeout=30)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface.py", line 209, in communicate_run
    run = self._make_run(run_obj)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface.py", line 159, in _make_run
    run._make_proto_run(proto_run)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 654, in _make_proto_run
    run.tags.append(tag)
TypeError: True has type bool, but expected one of: bytes, unicode
